### ISSUE TITLE
Laravel 5.8 does not support blade grammar.

### ISSUE THREAD

**Issue by kaysonwu** [hisorange/browser-detect#106]
The service container was delayed loading, resulting in `boot` not starting

**Comment by dschiller** [comment]
Laravel 5.8.18 and Blade: Directives ``@desktop`` and ``@enddesktop`` doesn't work. Didn't check the others. The Browser just display ``@desktop`` and ``@enddesktop`` instead of react on those Directives. Installed it with ``composer require hisorange/browser-detect`` nothing else. Also tried ``php artisan view:clear`` ( see https://github.com/riverskies/laravel-mobile-detect/issues/10 )

**Comment by pkkann** [comment]
I also have this exact issue :(
