### ISSUE TITLE
How to use with laravel lumen ?

### ISSUE THREAD

**Issue by emredusmez** [hisorange/browser-detect#163]
Hi, how to use with laravel lumen

**Comment by hisorange** [comment]
Yo, as far as I am aware, there is no difference between laravel / lumen usage, simply install the package, load it into the config and it's ready to be used.

As for use case, I would say there is not too much to do with it, since lumen is optimized for headless workloads, I seen a good tutorial where the programed used the package to track what kind of clients are logged in and gave a nice visual information to the end user about the logged in devices. But I wouldn't really use stateful authentication on an API.
