### ISSUE TITLE
Can i get language?

### ISSUE THREAD

**Issue by tongso** [hisorange/browser-detect#174]
how can i get language ?

**Comment by PoOwAa** [comment]
This package does not have language recognition, because the User-Agent does not contain it.

There are 2 ways to get your users language:
1. Check the request header for `accept-language` it will have something like: `hu-HU,hu;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6`. You can find more info here about [accept-language header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language)
2. Check on client-side with javascript: `window.navigator.language` more info about [NavigatorLanguage.language](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language)
