### ISSUE TITLE
Phone's user agent returns true on isTablet

### ISSUE THREAD

**Issue by suzakuchris** [hisorange/browser-detect#177]
Hello, I tried this library on my mobile phone (Xiaomi note series), which has this user agent

`
Mozilla/5.0 (Linux; Android 10; Redmi Note x Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Mobile Safari/537.36
`
and it returns true on isTablet even though its not a tablet, is there any planned fix or available workaround for this? thanks.

**Comment by hisorange** [comment]
Aye there, sadly the detection is not 1:1 which means that it is not possible to individually fix for each device because it would slow down the system to a halt. 

The detection is based on pattern matching and are executed by underlying detectors, in this case the isTablet coming from a detector which sees this as phablet.

In your case I would advise to handle the tablets and mobiles in the same way, because modern phones have bigger screen and better resolution than many tablet.

**Comment by suzakuchris** [comment]
ah, gotcha, thanks for responding, its a pretty good library you made, but I guess its true that we can't really detect everything for every edge cases, I'll see what I can do about it, maybe via CSS' breakpoint instead of PHP

**Comment by hisorange** [comment]
Yep yep! Breakpoints are much better solution, I only made this lib so pages which have a mobile and desktop version for optimalization can detect on server level and redirect the visitor without first loading a 200mb javascript on their mobile :D

Anyways, have a great day!
