### ISSUE TITLE
Latest version has wrong user agent retriever

### ISSUE THREAD

**Issue by nicxlau** [hisorange/browser-detect#189]
Create a new release with the fix of user agent retriever, for not depends of dev-stable, for prevent more bugs

**Comment by hisorange** [comment]
Hello @nicolauns will do a summarized release now. But as far as a see the issue was nothing else just a test used an old implementation and no bug in present.

Also, please consider using only released versions as the stable branch only means the development is stable enough to be merged, but it can cause small issues until the a release is drafted.

**Comment by hisorange** [comment]
Published in 4.5.2
