### ISSUE TITLE
PHP 8 and Laravel 10

### ISSUE THREAD

**Issue by diablo341** [hisorange/browser-detect#201]
Any idea when this project will support the latest PHP and Laravel?

**Comment by YassineDabbous** [comment]
PHP 8.1.9, Laravel 10 , no bugs ✅👌

**Comment by hisorange** [comment]
Oh my, let me vent my mind on this 😄 

I did wrote the code for Laravel 10.x and PHP8.2 updates, but some tests were failing and got pissed that it was working perfectly in local, but failed in the GH actions...

And I kinda forgot about :v

Thanks for the ping! Release 5.0.0 is out [here](https://github.com/hisorange/browser-detect/releases/tag/5.0.0)

~the issue was an outdated comments in the tests~
