### ISSUE TITLE
Opera is detected as Chrome

### ISSUE THREAD

**Issue by lezhnev74** [hisorange/browser-detect#41]
Hey! Just got this issue: Opera on Mac (probably on Win too) detects as Chrome.

Chrome user agent string:  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"
Opera's: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36 OPR/33.0.1990.115"

Opera has additional "OPR/33.0.1990.115".

**Comment by hisorange** [comment]
Thank you for the notice, I gona check if it's fixed by the UAParser plugin, but I see the problem in it since the UA contains the "Chrome/\d+" it's no wonder the parser identifying it as a Chrome this may need to be fixed by a custom plugin.

Anyway thanks, will release some kind of patch soon, if you pull the next update check the readme because the plugin addition requires the custom config to be changed.

**Comment by hisorange** [comment]
#76
