### ISSUE TITLE
Directives are not worked in blade for me!

### ISSUE THREAD

**Issue by zaxaco** [hisorange/browser-detect#97]
@mobile 
@endmobile

is not rendered in blade and echo in html

PHP 7.1.14 (cli) (built: Jan 31 2018 00:15:15) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Laravel Framework 5.6.25

I add service provider manually to app.php but still not work. also I try the following:
composer dump-autoload
php artisan clear-compiled
php artisan cache:clear

**Comment by jryd** [comment]
I can confirm that this issue occurs with all other directives too.
Laravel 5.7 and PHP7.1

**Comment by hisorange** [comment]
Checked the issue because this is in the current running tests too, and what I have seen is a provider cache in laravel, seems like if your providers are once cached the template registration is not executed again.

As summary, this happens when you have en existing installation and all the providers are cached + templates are generated, then the templates are not parsed again with the BD provider hooks.

Solution: Clean your provider cache __/bootstrap/cache__ dir, in the same session clear the __/storage/framework/view__ dir too.

**Comment by MikeDynamic** [comment]
Try php artisan view:clear after adding the provider and Alias, it worked for me.
